[package]
name = "oxv6"
version = "0.1.0"
edition = "2024"
authors = ["doroly"]
description = "🦀 A small RISC‑V learning operating system written in Rust"

[[bin]]
name = "oxv6"
path = "src/main.rs"
harness = false    # Disable the default test framework that relies on std

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"